# Generated by Django 4.2.7 on 2023-12-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('rs', 'RUPPEE')], default='RUPEE', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('eng', 'English'), ('hin', 'Hindi')], default='English', max_length=3),
        ),
    ]
