# Generated by Django 5.0 on 2023-12-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_currency_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('github', 'Github'), ('instagram', 'Instagram')], default='email', max_length=50),
        ),
    ]
